parameters:
#    scmdidms.example.class: SCM\DIDMSBundle\Example

services:
#    scmdidms.example:
#        class: %scmdidms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
