_welcome:
    pattern:  /
    defaults: { _controller: SCMDIDMSBundle:Default:index }

scmdidms:
    resource: "@SCMDIDMSBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
